### ISSUE TITLE
大佬您好，我想讲这个pdf阅读样式嵌入我的静态网页来显示pdf，请问可以实现吗？

### ISSUE THREAD

**Issue by LFG12** [luckyfuture0177/neat-reader#1]
大佬您好，我想讲这个pdf阅读样式嵌入我的静态网页来显示pdf，请问可以实现吗？
只需要样式即可，pdf文件由我本地添加
感谢大佬，祝您身体健康，生活愉快

**Comment by luckyfuture0177** [comment]
你好，我并不是这个项目的作者，我只是将此项目部署在GitHub page而已。你若是想在静态网站中加入pdf阅读功能，有许多开源项目可供参考，可搜索“静态网站 阅读器 pdf”等关键词。祝你工作顺利。
